name: Build Releases
on:
  release:
    types: [published]
  workflow_dispatch:
    
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  AUTH_SERVER_IP: ${{ secrets.AUTH_SERVER_IP }}

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - mipsel-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Install dependences
        run: sudo apt-get update -y && sudo apt-get install -y upx;

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          # 更新到最新的 nightly
          toolchain: nightly
          
      - name: Update dependencies
        run: cargo update
        
      - name: Install cross
        run: cargo install cross
        
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        shell: bash
        run: |
          compile_target=${{ matrix.target }}
          compile_compress="-u"

          cd build
          # Add -f tls to enable TLS feature
          ./build-release.sh -t ${{ matrix.target }} -f tls $compile_compress

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref, '-') }}
